apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-chat
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/koydas/ollama-chat.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama-chat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
